// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vxxoaZEoWTqm_k765GUjf-g9SH-x27k',
    appId: '1:68043613090:web:cd91454f6f0978adeac8fb',
    messagingSenderId: '68043613090',
    projectId: 'habit-tracker-f29f9',
    authDomain: 'habit-tracker-f29f9.firebaseapp.com',
    storageBucket: 'habit-tracker-f29f9.appspot.com',
    measurementId: 'G-7V2XC0R4D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34eVK-8V5xQESoV45zye9zUKTBADGX5U',
    appId: '1:68043613090:android:ac6f9ba2de181c47eac8fb',
    messagingSenderId: '68043613090',
    projectId: 'habit-tracker-f29f9',
    storageBucket: 'habit-tracker-f29f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSRS8mQX9ZNyFxgZK26onBaIDoSwbcvj0',
    appId: '1:68043613090:ios:ce89d04cc5a0c685eac8fb',
    messagingSenderId: '68043613090',
    projectId: 'habit-tracker-f29f9',
    storageBucket: 'habit-tracker-f29f9.appspot.com',
    iosClientId: '68043613090-tnmtnaekuofid48rt7jnk1mub8hslquq.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSRS8mQX9ZNyFxgZK26onBaIDoSwbcvj0',
    appId: '1:68043613090:ios:7e4ebc91eb4bdbbbeac8fb',
    messagingSenderId: '68043613090',
    projectId: 'habit-tracker-f29f9',
    storageBucket: 'habit-tracker-f29f9.appspot.com',
    iosClientId: '68043613090-hl7eq5r3t21u5f1phrts5nq351n5rsv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker.RunnerTests',
  );
}
